### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ianlulu** [IanLulu/neocities-website#2]
organize web pages, style sheets, and scripts to folders

- [ ] add favicons for each page
@ 11.21 17:46
&rarr; add srt car as favicon for simpleraytracer
- [ ] implement header, body, & footer sections
- [ ] organize files into respective directories (its starting to get crowded and hard to navigate)
- [ ] add figurine web ring link
- [ ] implement a gallery/portfolio page
&rarr; to use in gallery: [modal images](https://www.w3schools.com/howto/howto_css_modal_images.asp), [zoom on hover](https://www.w3schools.com/howto/howto_css_zoom_hover.asp), [lightbox](https://www.w3schools.com/howto/howto_js_lightbox.asp)
@ 11.23 15:12
&rarr; add a sketches page for my drawings, and separate pages for photos and the like (etc)
- [ ] add analytics to sites
&rarr; source: https://youtu.be/f3X-hYRxBL8?si=iLp9obEQglGT-8hy
- [ ] move "sources" comment in extras page to its own separate webpage. 
- [ ] make a shrine webpage as custom of websites in the old days. check out other sites for inspo:
&rarr; [chione](https://chione.neocities.org/ver8) & [hellstarares](https://hellstarares.neocities.org/) + dokodemo
&rarr; wiki page: https://fanlore.org/wiki/Character_Shrine
- [ ] add [gitlab](https://gitlab.com/lumpiabyte) link (p.s. refer to issue #1)
- [ ] add [rate your music](https://rateyourmusic.com/~NxUltra) link
@ 11.23 15:12
- [ ] plot out and add sitemap
- [ ] add a page for blogs and musings (abt random stuff or w/e)
&rarr; 2024-03-14 19:16 to use in blogs/dev diary: [sticky header how to](https://www.w3schools.com/howto/howto_js_sticky_header.asp), [sticky header example](https://css-tricks.com/sticky-table-of-contents-with-scrolling-active-states/)
#### @ 2024-01-25 19:47
- [ ] add pinterest, instagram, and stats.fm profiles
#### @ 2024-03-03 19:19
- [ ] add development diary along with blogs (inspired by Splatoon 3 Marina's Dev Diaries)
##### @ 03-04 08:27
- [ ] add [pcpartpicker](https://pcpartpicker.com/b/YPn7YJ) link

**Comment by IanLulu** [comment]
- [ ] add favicons for each page

**Comment by ianlulu** [comment]
i should probably make a separate issue cause this todo list is starting to pile up lol
